<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#NumPy数组计算" data-toc-modified-id="NumPy数组计算-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>NumPy数组计算</a></span></li><li><span><a href="#数组与标量的算术运算" data-toc-modified-id="数组与标量的算术运算-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>数组与标量的算术运算</a></span></li><li><span><a href="#数组与数组之间的运算" data-toc-modified-id="数组与数组之间的运算-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>数组与数组之间的运算</a></span></li></ul></div>

## NumPy数组计算

In [3]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

## 数组与标量的算术运算

In [4]:
arr * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [5]:
arr + 2

array([[3, 4, 5],
       [6, 7, 8]])

## 数组与数组之间的运算

In [6]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [7]:
arr * arr # 矩阵乘法在线性代数里面会讲

array([[ 1,  4,  9],
       [16, 25, 36]])

In [8]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
arr / arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# *=、+=运算会修改原对象，而不是创建新对象
arr *= 2
arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [12]:
# shape相同的数组之间比较会生成布尔数组
arr2 = arr + 1
arr2 > arr

array([[ True,  True,  True],
       [ True,  True,  True]])

In [13]:
# 不同类型的数组计算之后的结果的类型会向上转换为更精确的类型（如int类型的数组a和float类型的数组b求和得到c的类型为float，而不是int）
int_arr = np.array([1, 2, 3])
float_arr = np.array([0.1, 0.2, 0.3])

res_arr = int_arr + float_arr
res_arr.dtype

dtype('float64')

In [14]:
# 形状不同的数组之间能否进行计算？
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3, 4])

arr1 + arr2

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [15]:
arr3 = np.array([[1, 2, 3],
                 [1, 2, 3]])

arr1 + arr3

array([[2, 4, 6],
       [2, 4, 6]])