<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#排序" data-toc-modified-id="排序-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>排序</a></span><ul class="toc-item"><li><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#多维数组排序" data-toc-modified-id="多维数组排序-1.0.0.1"><span class="toc-item-num">1.0.0.1&nbsp;&nbsp;</span>多维数组排序</a></span></li><li><span><a href="#按键排序" data-toc-modified-id="按键排序-1.0.0.2"><span class="toc-item-num">1.0.0.2&nbsp;&nbsp;</span>按键排序</a></span></li></ul></li></ul></li></ul></li></ul></div>

## 排序

sort(a[, axis, kind, order])

返回数组的排序副本

ndarray.sort([axis, kind, order])

就地对数组进行排序

lexsort(keys[, axis])

使用一系列键执行间接排序

argsort(a[, axis, kind, order])

返回对数组进行排序的索引

msort(a)

返回沿第一个轴排序的数组副本

sort_complex(a)

首先使用实部对复杂数组进行排序，然后使用虚部进行排序

partition(a, kth[, axis, kind, order])

返回数组的分区副本

argpartition(a, kth[, axis, kind, order])

使用kind关键字指定的算法沿给定轴执行间接分区

In [1]:
import numpy as np

arr1 = np.random.randn(10)
arr1

array([ 0.08432723, -0.92847027, -0.34126329, -0.83387423,  1.37230036,
        1.59632423,  0.59059831, -0.97828575, -0.24285715,  1.41108744])

In [2]:
np.sort(arr1)

array([-0.97828575, -0.92847027, -0.83387423, -0.34126329, -0.24285715,
        0.08432723,  0.59059831,  1.37230036,  1.41108744,  1.59632423])

In [3]:
arr1.sort() # 就地进行排序，修改原数组
arr1

array([-0.97828575, -0.92847027, -0.83387423, -0.34126329, -0.24285715,
        0.08432723,  0.59059831,  1.37230036,  1.41108744,  1.59632423])

##### 多维数组排序

In [4]:
arr2 = np.random.randn(3, 4)
arr2

array([[ 0.48553688,  0.19115807,  1.20750953, -0.48682379],
       [-0.5492065 ,  0.56615595,  0.08772585,  0.34906975],
       [ 0.63809466,  0.90298   , -1.83388261, -0.02325801]])

In [5]:
np.sort(arr2, axis=1) # 按列排序

array([[-0.48682379,  0.19115807,  0.48553688,  1.20750953],
       [-0.5492065 ,  0.08772585,  0.34906975,  0.56615595],
       [-1.83388261, -0.02325801,  0.63809466,  0.90298   ]])

In [6]:
np.sort(arr2, axis=0) # 按行排序

array([[-0.5492065 ,  0.19115807, -1.83388261, -0.48682379],
       [ 0.48553688,  0.56615595,  0.08772585, -0.02325801],
       [ 0.63809466,  0.90298   ,  1.20750953,  0.34906975]])

In [7]:
my_dt = np.dtype([('name',  'U10'),('age',  int)]) # 按关键字排序
my_dt

dtype([('name', '<U10'), ('age', '<i4')])

##### 按键排序

In [8]:
arr3 = np.array([("罗志祥", 21), ("黄渤", 25), ("孙红雷",  17),  ("黄磊",27)], dtype=my_dt)
arr3

array([('罗志祥', 21), ('黄渤', 25), ('孙红雷', 17), ('黄磊', 27)],
      dtype=[('name', '<U10'), ('age', '<i4')])

In [9]:
np.sort(arr3, order='age')

array([('孙红雷', 17), ('罗志祥', 21), ('黄渤', 25), ('黄磊', 27)],
      dtype=[('name', '<U10'), ('age', '<i4')])