<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#总结" data-toc-modified-id="总结-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>总结</a></span></li><li><span><a href="#拷贝" data-toc-modified-id="拷贝-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>拷贝</a></span></li><li><span><a href="#完全不拷贝" data-toc-modified-id="完全不拷贝-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>完全不拷贝</a></span></li><li><span><a href="#浅拷贝" data-toc-modified-id="浅拷贝-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>浅拷贝</a></span></li><li><span><a href="#深拷贝" data-toc-modified-id="深拷贝-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>深拷贝</a></span></li></ul></div>

## 总结

**自学知识点数：**4

**代码示例：**13

In [15]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## 拷贝

NumPy中拷贝分为三种情况：

完全不拷贝

一个数组的任何变化都反映在另一个数组上，包括值变化和形状变化

浅拷贝

一个数组值会变化会反映在另一个数组上，但是形状不变化

深拷贝

创建原数组的副本，副本的任何变化都不会反映在原数组上

In [16]:
import numpy as np

## 完全不拷贝

In [17]:
a = np.arange(12)
b = a
print(a)
b

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
b[5] = 500
a
b

array([  0,   1,   2,   3,   4, 500,   6,   7,   8,   9,  10,  11])

array([  0,   1,   2,   3,   4, 500,   6,   7,   8,   9,  10,  11])

In [19]:
b is a

True

In [20]:
b.shape = (2, 6)
a
b

array([[  0,   1,   2,   3,   4, 500],
       [  6,   7,   8,   9,  10,  11]])

array([[  0,   1,   2,   3,   4, 500],
       [  6,   7,   8,   9,  10,  11]])

## 浅拷贝

In [21]:
a = np.arange(12)
c = a.view()
a
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
c is a

False

In [23]:
c.base is a

True

In [24]:
c[2] = 200
a
c

array([  0,   1, 200,   3,   4,   5,   6,   7,   8,   9,  10,  11])

array([  0,   1, 200,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [25]:
c.shape = (12, 1)
a
c

array([  0,   1, 200,   3,   4,   5,   6,   7,   8,   9,  10,  11])

array([[  0],
       [  1],
       [200],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9],
       [ 10],
       [ 11]])

## 深拷贝

In [26]:
a = np.arange(12)
d = a.copy()
a
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
d is a

False

In [28]:
a[1] = 100
a
d

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
d.shape = (12, 1)
a
d

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])