<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#总结" data-toc-modified-id="总结-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>总结</a></span></li><li><span><a href="#ndarray的创建方式" data-toc-modified-id="ndarray的创建方式-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>ndarray的创建方式</a></span><ul class="toc-item"><li><span><a href="#np.array()" data-toc-modified-id="np.array()-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>np.array()</a></span></li><li><span><a href="#np.asarray()" data-toc-modified-id="np.asarray()-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>np.asarray()</a></span></li><li><span><a href="#np.zeros()" data-toc-modified-id="np.zeros()-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>np.zeros()</a></span></li><li><span><a href="#np.zeros_like()" data-toc-modified-id="np.zeros_like()-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>np.zeros_like()</a></span></li><li><span><a href="#np.ones()" data-toc-modified-id="np.ones()-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>np.ones()</a></span></li><li><span><a href="#np.ones_like()" data-toc-modified-id="np.ones_like()-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>np.ones_like()</a></span></li><li><span><a href="#np.empty()" data-toc-modified-id="np.empty()-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>np.empty()</a></span></li><li><span><a href="#np.empty_like()" data-toc-modified-id="np.empty_like()-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>np.empty_like()</a></span></li><li><span><a href="#np.full()" data-toc-modified-id="np.full()-2.9"><span class="toc-item-num">2.9&nbsp;&nbsp;</span>np.full()</a></span></li><li><span><a href="#np.full_like()" data-toc-modified-id="np.full_like()-2.10"><span class="toc-item-num">2.10&nbsp;&nbsp;</span>np.full_like()</a></span></li><li><span><a href="#np.eye()" data-toc-modified-id="np.eye()-2.11"><span class="toc-item-num">2.11&nbsp;&nbsp;</span>np.eye()</a></span></li><li><span><a href="#np.identity()" data-toc-modified-id="np.identity()-2.12"><span class="toc-item-num">2.12&nbsp;&nbsp;</span>np.identity()</a></span></li><li><span><a href="#np.random" data-toc-modified-id="np.random-2.13"><span class="toc-item-num">2.13&nbsp;&nbsp;</span>np.random</a></span></li><li><span><a href="#np.arange()" data-toc-modified-id="np.arange()-2.14"><span class="toc-item-num">2.14&nbsp;&nbsp;</span>np.arange()</a></span></li><li><span><a href="#np.linspace()" data-toc-modified-id="np.linspace()-2.15"><span class="toc-item-num">2.15&nbsp;&nbsp;</span>np.linspace()</a></span></li><li><span><a href="#np.fromfunction()" data-toc-modified-id="np.fromfunction()-2.16"><span class="toc-item-num">2.16&nbsp;&nbsp;</span>np.fromfunction()</a></span></li><li><span><a href="#np.fromfile()" data-toc-modified-id="np.fromfile()-2.17"><span class="toc-item-num">2.17&nbsp;&nbsp;</span>np.fromfile()</a></span></li></ul></li></ul></div>

## 总结

**自学知识点数：**17

**代码示例：**17

## ndarray的创建方式

### np.array()

将输入的列表、元组、数组等序列类型转换我ndaray对象

In [1]:
import numpy as np

# data1也可以是tuple类型
# data1可以进行嵌套
data = [[1,2,3], [4,5,6]]
arr1 = np.array(data)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

### np.asarray()

array()和asarray()都可以将结构数据转化为ndarray，但是主要区别就是当数据源是ndarray时，array仍然会copy出一个副本，占用新的内存，但asarray不会

In [2]:
arr2 = np.asarray(arr1)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

### np.zeros()

根据指定形状创建一个全为0的ndarray对象

In [3]:
arr3 = np.zeros([3, 4])
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.zeros_like()

传入一个数组作为参数，根据该数组的形状和dtype创建一个全0的ndaray对象

In [4]:
arr4 = np.zeros_like(data)
arr4

array([[0, 0, 0],
       [0, 0, 0]])

### np.ones()

根据指定形状创建一个全为1的ndarray对象

In [5]:
arr5 = np.ones([2, 3])
arr5

array([[1., 1., 1.],
       [1., 1., 1.]])

### np.ones_like()

传入一个数组作为参数，根据该数组的形状和dtype创建一个全1的ndaray对象

In [6]:
arr6 = np.ones_like(data)
arr6

array([[1, 1, 1],
       [1, 1, 1]])

### np.empty()

根据指定形状创建ndarray对象，只分配内存但是不填充任何值

In [7]:
# 可以直接在终端中演示
arr7 = np.empty([2, 2]) 
arr7

array([[9.6967423e-312, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000]])

### np.empty_like()

同上

In [8]:
arr8 = np.empty_like(data)
arr8

array([[-145422048,        456,          0],
       [         0,          1,        456]])

### np.full()

根据指定形状传建一个ndarray对象，并用fill_value的值进行填充

In [9]:
arr9 = np.full([2,3], fill_value=3)
arr9

array([[3, 3, 3],
       [3, 3, 3]])

### np.full_like()

传入一个数组作为参数，根据该数组的形状创建一个ndarray对象，并用fill_value的值进行填充

In [10]:
arr10 = np.full_like(data, 8)
arr10

array([[8, 8, 8],
       [8, 8, 8]])

### np.eye()

传入一个整数N，创建一个N * N的单位矩阵

In [11]:
"""
numpy.eye(N, M=None, k=0, dtype=<class‘float’>, order=’C’)
N: 行数
M：列数，默认等于N
k：对角线索引：0（默认）为主对角线，正值是指上对角线，负值是指到下对角线
order: {'C', 'F'}输出是否应存储在主要行（C样式）中或内存中的列主（Fortran样式）顺序
"""
arr12 = np.eye(5)
arr12

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### np.identity()

传入一个整数N，创建一个N * N的单位矩阵

In [12]:
# numpy.identity(n, dtype=None)
arr11 = np.identity(5)
arr11

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### np.random

随机抽样创建

In [13]:
arr13 = np.random.randn(2, 3)
arr13

array([[-0.10692708,  0.80057481,  0.06773064],
       [ 0.67000052,  1.61981546, -1.17182764]])

### np.arange()

在给定间隔内返回均匀间隔的值（一维数组）

In [14]:
"""
参数
start：开始位置，数字，可选，默认值为0
stop：结束位置，数字，
step：步长，数字，可选，默认为1。如果指定step则必须指定start
dtype：类型。不指定则自动推断
"""
arr14 = np.arange(start=0, stop=10, step=2)
arr14

array([0, 2, 4, 6, 8])

### np.linspace()

返回指定间隔内的等距数字。

In [15]:
arr15 = np.linspace(0, 10, 5)
arr15

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### np.fromfunction()

通过对每个坐标执行函数来构造数组

In [16]:
def fun(x, y):
    return x * 10 + y

np.fromfunction(fun, (4, 5), dtype=np.int)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

### np.fromfile()

从文本或二进制文件中的数据构造数组

np.fromfile(file, dtype=float, count=-1, sep='')

file：要打开的文件对象或者文件名

dtype：返回数组的数据类型。对于二进制文件，它用于确定文件中项目的大小和字节顺序。错误的数据类型会返回错误的数据

count：要读取的项目数。-1表示所有项目（即完整文件）

sep：如果文件是文本文件，则表示分隔项之间的分隔符。空（“”）分隔符表示应将文件视为二进制文件。分隔符中的空格（“”）与零个或多个空白字符匹配。仅由空格组成的分隔符必须至少与一个空格匹配

In [17]:
np.fromfile('./file/intfile') # 默认的dtype是floatdef my_dot(a, b):
 

FileNotFoundError: [Errno 2] No such file or directory: './file/intfile'

 np.fromfunction(lambda i,j:i+j,(2, 3))