<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#广播" data-toc-modified-id="广播-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>广播</a></span><ul class="toc-item"><li><span><a href="#广播的原则" data-toc-modified-id="广播的原则-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>广播的原则</a></span></li></ul></li></ul></div>

## 广播
广播是指不同形状的数组之间的算术运算的执行方式。受限于某些约束，较小的数组依据较大数组“broadcasting”，使得它们具有兼容的形状。

### 广播的原则

如果两个数组的后缘维度（即从末尾开始算起的维度）的轴长度相符或其中一方的长度为1，则认为它们是广播兼容的。广播会在缺失和（或）长度为1的维度上进行。



In [3]:
import numpy as np

arr1 = np.arange(24).reshape(3,4,2)
arr2 = np.array([[4],
                [4],
                [4],
                [4]])
arr1
arr2

array([[4],
       [4],
       [4],
       [4]])

In [9]:
arr1+2

array([[[ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23],
        [24, 25]]])

In [10]:
arr1-5

array([[[-5, -4],
        [-3, -2],
        [-1,  0],
        [ 1,  2]],

       [[ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18]]])

In [11]:
arr1/2

array([[[ 0. ,  0.5],
        [ 1. ,  1.5],
        [ 2. ,  2.5],
        [ 3. ,  3.5]],

       [[ 4. ,  4.5],
        [ 5. ,  5.5],
        [ 6. ,  6.5],
        [ 7. ,  7.5]],

       [[ 8. ,  8.5],
        [ 9. ,  9.5],
        [10. , 10.5],
        [11. , 11.5]]])

In [12]:
arr1%2

array([[[0, 1],
        [0, 1],
        [0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1],
        [0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1],
        [0, 1],
        [0, 1]]], dtype=int32)

In [4]:
arr1 * 3

array([[[ 0,  3],
        [ 6,  9],
        [12, 15],
        [18, 21]],

       [[24, 27],
        [30, 33],
        [36, 39],
        [42, 45]],

       [[48, 51],
        [54, 57],
        [60, 63],
        [66, 69]]])

In [5]:
arr1.shape
arr2.shape

(4, 1)

In [13]:
arr1 +arr2

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27]]])

In [14]:
arr1 * arr2

array([[[ 0,  4],
        [ 8, 12],
        [16, 20],
        [24, 28]],

       [[32, 36],
        [40, 44],
        [48, 52],
        [56, 60]],

       [[64, 68],
        [72, 76],
        [80, 84],
        [88, 92]]])

In [15]:
arr1 / arr2

array([[[0.  , 0.25],
        [0.5 , 0.75],
        [1.  , 1.25],
        [1.5 , 1.75]],

       [[2.  , 2.25],
        [2.5 , 2.75],
        [3.  , 3.25],
        [3.5 , 3.75]],

       [[4.  , 4.25],
        [4.5 , 4.75],
        [5.  , 5.25],
        [5.5 , 5.75]]])

In [16]:
arr1 % arr2

array([[[0, 1],
        [2, 3],
        [0, 1],
        [2, 3]],

       [[0, 1],
        [2, 3],
        [0, 1],
        [2, 3]],

       [[0, 1],
        [2, 3],
        [0, 1],
        [2, 3]]], dtype=int32)

In [17]:
arr1 - arr2

array([[[-4, -3],
        [-2, -1],
        [ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [7]:
arr3 = np.arange(48).reshape((8, 1, 6, 1))
arr4 = np.arange(35).reshape((7, 1, 5))
arr3.shape
arr4.shape

(7, 1, 5)

In [8]:
arr3 - arr4

array([[[[  0,  -1,  -2,  -3,  -4],
         [  1,   0,  -1,  -2,  -3],
         [  2,   1,   0,  -1,  -2],
         [  3,   2,   1,   0,  -1],
         [  4,   3,   2,   1,   0],
         [  5,   4,   3,   2,   1]],

        [[ -5,  -6,  -7,  -8,  -9],
         [ -4,  -5,  -6,  -7,  -8],
         [ -3,  -4,  -5,  -6,  -7],
         [ -2,  -3,  -4,  -5,  -6],
         [ -1,  -2,  -3,  -4,  -5],
         [  0,  -1,  -2,  -3,  -4]],

        [[-10, -11, -12, -13, -14],
         [ -9, -10, -11, -12, -13],
         [ -8,  -9, -10, -11, -12],
         [ -7,  -8,  -9, -10, -11],
         [ -6,  -7,  -8,  -9, -10],
         [ -5,  -6,  -7,  -8,  -9]],

        ...,

        [[-20, -21, -22, -23, -24],
         [-19, -20, -21, -22, -23],
         [-18, -19, -20, -21, -22],
         [-17, -18, -19, -20, -21],
         [-16, -17, -18, -19, -20],
         [-15, -16, -17, -18, -19]],

        [[-25, -26, -27, -28, -29],
         [-24, -25, -26, -27, -28],
         [-23, -24, -25, -26, -27],
      